/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.projetoclinica.view;

import br.com.projetoclinica.modelConnection.ConexaoBD;
import br.com.prjetoclinica.controller.MedicoController;
import br.com.prjetoclinica.modelEntities.Medico;
import br.com.projetoclinica.modelDAO.MedicoDAO;
import java.sql.SQLException;
import javax.swing.JButton;

import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.JTextField;

/**
 *
 * @author victor
 */
public class FormMedico extends javax.swing.JFrame {

    Medico med = new Medico();
    ConexaoBD conex = new ConexaoBD();
    private final MedicoController medController;
    MedicoDAO md = new MedicoDAO();
   
    
    public FormMedico() {
        initComponents();
        medController = new MedicoController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jFormattedTextFieldCrm = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jComboBoxExpecializacao = new javax.swing.JComboBox();
        jButtonNovo = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonPesquisar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMedico = new javax.swing.JTable();
        jTextFieldPesquisa = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        jLabel3.setText("Crm:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(119, 103, 30, 30);

        jLabel2.setText("Nome:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(111, 56, 40, 40);

        jFormattedTextFieldCrm.setEnabled(false);
        jPanel1.add(jFormattedTextFieldCrm);
        jFormattedTextFieldCrm.setBounds(150, 100, 160, 30);

        jLabel4.setText("Expecialização:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(500, 60, 80, 30);

        jTextFieldNome.setEnabled(false);
        jTextFieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldNome);
        jTextFieldNome.setBounds(149, 60, 340, 30);

        jComboBoxExpecializacao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cirurgião" }));
        jPanel1.add(jComboBoxExpecializacao);
        jComboBoxExpecializacao.setBounds(580, 60, 110, 30);

        jButtonNovo.setText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonNovo);
        jButtonNovo.setBounds(12, 34, 81, 30);

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSalvar);
        jButtonSalvar.setBounds(12, 70, 81, 32);

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setEnabled(false);
        jPanel1.add(jButtonCancelar);
        jButtonCancelar.setBounds(12, 108, 80, 32);

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.setEnabled(false);
        jPanel1.add(jButtonExcluir);
        jButtonExcluir.setBounds(12, 184, 81, 32);

        jButtonEditar.setText("Editar");
        jButtonEditar.setEnabled(false);
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEditar);
        jButtonEditar.setBounds(12, 146, 81, 32);

        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonPesquisar);
        jButtonPesquisar.setBounds(380, 140, 80, 30);

        jTableMedico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableMedico);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(111, 190, 563, 200);

        jTextFieldPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPesquisaActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldPesquisa);
        jTextFieldPesquisa.setBounds(150, 140, 220, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(23, 43, 710, 410);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Cadastro de Médicos");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(271, 13, 183, 24);

        setSize(new java.awt.Dimension(769, 502));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        jTextFieldNome.setEnabled(true);
        jFormattedTextFieldCrm.setEnabled(true);
        jButtonSalvar.setEnabled(true);
        jComboBoxExpecializacao.setEnabled(true);
        
        
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
       med.setNome(jTextFieldNome.getText());
        med.setExpecialidade((String)jComboBoxExpecializacao.getSelectedItem());
        med.setCrm(Integer.parseInt(jFormattedTextFieldCrm.getText()));
        md.salvar(med);
        jTextFieldNome.setEnabled(false);
        jFormattedTextFieldCrm.setEnabled(false);
        jComboBoxExpecializacao.setEnabled(false);
        jButtonSalvar.setEnabled(false);
     
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jTextFieldPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPesquisaActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
         /*Utilizamos aqui o método encapsulado set para pegar o que o usuário digitou no campo txtPesquisa
        Youtube:https://www.youtube.com/watch?v=v1ERhLdmf98*/
        med.setPesquisa(jTextFieldPesquisa.getText());
        
        Medico modelo;

        try {
            modelo = md.buscarPor(med);
            if (modelo != null) {
                jTextFieldNome.setText(modelo.getNome());
                /**
                 * String.valueOf() pega um Valor Inteiro e transforma em String
                 * e seta em jFormattedTextFieldCRM que é um campo do tipo texto
                 */
               jFormattedTextFieldCrm.setText((String.valueOf(modelo.getCrm())));
                /*Para setarmos um campos Combobox utilizamos o método setSelectedItem**/
                jComboBoxExpecializacao.setSelectedItem(modelo.getExpecialidade());

                /**
                 * Liberar os botões abaixo
                 */
                jButtonEditar.setEnabled(true);
                jButtonExcluir.setEnabled(true);
            } else {
                JOptionPane.showMessageDialog(null, "Médico não Cadastrado");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro na camada gui FormMedico" + ex.getMessage());
        }
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMedico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox jComboBoxExpecializacao;
    private javax.swing.JFormattedTextField jFormattedTextFieldCrm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMedico;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldPesquisa;
    // End of variables declaration//GEN-END:variables

    public JComboBox getjComboBoxExpecializacao() {
        return jComboBoxExpecializacao;
    }

    public void setjComboBoxExpecializacao(JComboBox jComboBoxExpecializacao) {
        this.jComboBoxExpecializacao = jComboBoxExpecializacao;
    }

    public JFormattedTextField getjFormattedTextFieldCrm() {
        return jFormattedTextFieldCrm;
    }

    public void setjFormattedTextFieldCrm(JFormattedTextField jFormattedTextFieldCrm) {
        this.jFormattedTextFieldCrm = jFormattedTextFieldCrm;
    }

    public JTextField getjTextFieldNome() {
        return jTextFieldNome;
    }

    public void setjTextFieldNome(JTextField jTextFieldNome) {
        this.jTextFieldNome = jTextFieldNome;
    }

    public JButton getjButtonPesquisar() {
        return jButtonPesquisar;
    }

    public void setjButtonPesquisar(JButton jButtonPesquisar) {
        this.jButtonPesquisar = jButtonPesquisar;
    }

    

}
