/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.projetoclinica.view;

import javax.swing.JOptionPane;

/**
 *
 * @author victor
 */
public class TelaLogin extends javax.swing.JFrame {

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelUsuario = new javax.swing.JLabel();
        jButtonSair = new javax.swing.JButton();
        jToggleButtonAcessar = new javax.swing.JToggleButton();
        jLabelSenha = new javax.swing.JLabel();
        jTextFieldCampoUsuario = new javax.swing.JTextField();
        jPasswordFieldCampoSenha = new javax.swing.JPasswordField();
        jLabelTituloLogin = new javax.swing.JLabel();
        jLabelFundoLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabelUsuario.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelUsuario.setForeground(new java.awt.Color(51, 51, 51));
        jLabelUsuario.setText("Usuário:");
        getContentPane().add(jLabelUsuario);
        jLabelUsuario.setBounds(80, 140, 70, 30);

        jButtonSair.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSair);
        jButtonSair.setBounds(290, 230, 60, 30);

        jToggleButtonAcessar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jToggleButtonAcessar.setText("Acessar");
        jToggleButtonAcessar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonAcessarActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButtonAcessar);
        jToggleButtonAcessar.setBounds(190, 230, 80, 30);

        jLabelSenha.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelSenha.setForeground(new java.awt.Color(51, 51, 51));
        jLabelSenha.setText("Senha:");
        getContentPane().add(jLabelSenha);
        jLabelSenha.setBounds(90, 180, 60, 30);

        jTextFieldCampoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCampoUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldCampoUsuario);
        jTextFieldCampoUsuario.setBounds(150, 140, 260, 30);

        jPasswordFieldCampoSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldCampoSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordFieldCampoSenha);
        jPasswordFieldCampoSenha.setBounds(150, 182, 260, 30);

        jLabelTituloLogin.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabelTituloLogin.setForeground(new java.awt.Color(51, 51, 51));
        jLabelTituloLogin.setText("Login");
        getContentPane().add(jLabelTituloLogin);
        jLabelTituloLogin.setBounds(210, 60, 110, 50);

        jLabelFundoLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundotelaLogin.png"))); // NOI18N
        getContentPane().add(jLabelFundoLogin);
        jLabelFundoLogin.setBounds(-10, 0, 500, 350);

        setSize(new java.awt.Dimension(507, 379));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jToggleButtonAcessarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonAcessarActionPerformed
        if(jTextFieldCampoUsuario.getText().equals("admin") &&
            jPasswordFieldCampoSenha.getText().equals("1234")){
            TelaPrincipal telaP = new TelaPrincipal();
            telaP.setVisible(true);
            dispose();
        }else{
            JOptionPane.showMessageDialog(rootPane, "Senha ou Usuário Invalidos!!");
        }
    }//GEN-LAST:event_jToggleButtonAcessarActionPerformed

    private void jPasswordFieldCampoSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldCampoSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldCampoSenhaActionPerformed

    private void jTextFieldCampoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCampoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCampoUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSair;
    private javax.swing.JLabel jLabelFundoLogin;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JLabel jLabelTituloLogin;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPasswordField jPasswordFieldCampoSenha;
    private javax.swing.JTextField jTextFieldCampoUsuario;
    private javax.swing.JToggleButton jToggleButtonAcessar;
    // End of variables declaration//GEN-END:variables
}
